name       : intel-graphics-compiler
version    : 1.0.11378
release    : 8
source     :
    - https://github.com/intel/intel-graphics-compiler/archive/refs/tags/igc-1.0.11378.tar.gz : 527229e8b7d7773e128a12fa5577ea0193643479b0bc23906d9872384604a7dc
license    : MIT
component  : programming.tools
homepage   : https://github.com/intel/intel-graphics-compiler/
summary    : An LLVM-based compiler for OpenCL on Intel Gen graphics
description: |
    The Intel® Graphics Compiler for OpenCL™ is an LLVM based compiler for OpenCL™ targeting Intel Gen graphics hardware architecture.
clang      : yes
builddeps  :
    - spirv-tools-devel
    - opencl-clang-devel
    - spirv-headers
    - spirv-llvm-translator-devel
    - vc-intrinsics
setup      : |
    %patch -p1 < $pkgfiles/fix-zlib-linking.patch
    %patch -p1 < $pkgfiles/llvm14.patch

    # disable warnings as errors
    sed -i 's|-Werror||g' IGC/CMakeLists.txt
    %cmake_ninja \
        -DINSTALL_SPIRVDLL=OFF \
        -DIGC_OPTION__ARCHITECTURE_TARGET='Linux64' \
        -DIGC_OPTION__LLVM_PREFERRED_VERSION=`llvm-config --version` \
        -DIGC_OPTION__LLVM_MODE=Prebuilds \
        -DIGC_OPTION__CLANG_MODE=Prebuilds \
        -DIGC_OPTION__LLD_MODE=Prebuilds \
        -DIGC_OPTION__LINK_KHRONOS_SPIRV_TRANSLATOR=ON \
        -DIGC_OPTION__USE_PREINSTALLED_SPRIV_HEADERS=ON \
        -DIGC_OPTION__SPIRV_TOOLS_MODE=Prebuilds \
        -DIGC_OPTION__SPIRV_TRANSLATOR_MODE=Prebuilds \
        -DIGC_OPTION__VC_INTRINSICS_MODE=Prebuilds \
        -DINSTALL_GENX_IR=ON \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
