name       : intel-graphics-compiler
version    : 1.0.9441
release    : 7
source     :
    - https://github.com/intel/intel-graphics-compiler/archive/refs/tags/igc-1.0.9441.tar.gz : b9fdde261d666d549f05932bb015022404125e7146ffdf0813de643f82ce0742
    - git|https://github.com/KhronosGroup/SPIRV-Tools.git : v2021.4
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : sdk-1.2.198.0
license    : MIT
component  : programming.tools
homepage   : https://github.com/intel/intel-graphics-compiler/
summary    : An LLVM-based compiler for OpenCL on Intel Gen graphics
description: |
    The Intel® Graphics Compiler for OpenCL™ is an LLVM based compiler for OpenCL™ targeting Intel Gen graphics hardware architecture.
clang      : yes
builddeps  :
    - opencl-clang-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-includes-to-SWSB_G4IR.cpp.patch
    %patch -p1 < $pkgfiles/0001-Remove-default-value-for-SPIRV-Tools-dir.patch
    %patch -p1 < $pkgfiles/0004-link-pthread.patch
    %patch -p1 < $pkgfiles/210.patch

    # disable warnings as errors
    sed -i 's|-Werror||g' IGC/CMakeLists.txt
    %cmake \
        -DVC_INTRINSICS_SRC="$sources/vc-intrinsics.git" \
        -DINSTALL_SPIRVDLL=OFF \
        -DIGC_OPTION__ARCHITECTURE_TARGET='Linux64' \
        -DIGC_OPTION__LLVM_PREFERRED_VERSION="13.0.0" \
        -DIGC_OPTION__LLVM_FROM_SYSTEM=TRUE \
        -DINSTALL_GENX_IR=ON \
        -DIGC_BUILD__VC_ENABLED=OFF \
        -DSPIRV-Tools_SOURCE_DIR="$sources/SPIRV-Tools.git" \
        -DSPIRV-Headers_SOURCE_DIR="$sources/SPIRV-Headers.git" \
        -Wno-dev
build      : |
    %make
install    : |
    %make_install
