name       : intel-graphics-compiler
version    : 1.0.6712
release    : 2
source     :
    - https://github.com/intel/intel-graphics-compiler/archive/refs/tags/igc-1.0.6712.tar.gz : 1e5d63337ccbf8304c34b045b66e6e8411ce7d95b8f34c5abff17f6e60033eb0
    - git|https://github.com/intel/vc-intrinsics.git : d7c5f99bd910a681b907815ebd44ef319ff417c4
license    : MIT
component  : programming.tools
homepage   : https://github.com/intel/intel-graphics-compiler/
summary    : An LLVM-based compiler for OpenCL on Intel Gen graphics
description: |
    The Intel® Graphics Compiler for OpenCL™ is an LLVM based compiler for OpenCL™ targeting Intel Gen graphics hardware architecture.
clang      : yes
builddeps  :
    - opencl-clang-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Resolve-compatibility-issues-with-llvm-11.patch

    # disable warnings as errors
    sed -i 's|-Werror||g' IGC/CMakeLists.txt
    %cmake \
        -DVC_INTRINSICS_SRC="$sources/vc-intrinsics.git" \
        -DINSTALL_SPIRVDLL=OFF \
        -DIGC_OPTION__ARCHITECTURE_TARGET='Linux64' \
        -DIGC_OPTION__LLVM_PREFERRED_VERSION="11.1.0" \
        -DIGC_OPTION__LLVM_FROM_SYSTEM=TRUE \
        -DINSTALL_GENX_IR=ON \
        -DIGC_BUILD__VC_ENABLED=OFF \
        -Wno-dev
build      : |
    %make
install    : |
    %make_install
